version: "3"

services:
  debatedb:
    container_name: debatedb
    build:
      context: .
      dockerfile: exilliar/debatedb-frontend:latest
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - "8081:8080"
